apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: springweb-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@github.com:Orion83-h/springweb-app.git'
    targetRevision: main
    path: .
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: webapp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
