apiVersion: apps/v1
kind: Deployment
metadata:
  name: springweb-app
  labels:
    app: springweb-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springweb-app
  template:
    metadata:
      labels:
        app: springweb-app
    spec:
      containers:
        - name: java-app
          image: colanta06/java-app:v1
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 3
            timeoutSeconds: 1
            failureThreshold: 3