apiVersion: v1
kind: Service
metadata:
  name:  springweb-app
  labels:
  app: springweb-app
spec:
  type: NodePort
  ports:
    - port: 50000
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
   app:springweb-app 
